"""
XGBoost Flood Susceptibility Model — Assam 4 Districts
Extends Nagaon 2026 Geocarto International paper methodology:
  https://www.tandfonline.com/doi/abs/10.1080/10106049.2026.2677319

Phase 1 (this script): static terrain features only — validates XGBoost
baseline against the RF model (ROC-AUC 0.889) before adding dynamics.
Phase 2 (future): add GloFAS Q_anomaly + ERA5 5-day rainfall + soil moisture.

Features (static):
  elevation, slope, TWI, flow_acc  (from FABDEM via pysheds, same as RF)

Labels:
  1 = flood  (from data/gfm_validation/*.tif)
  0 = no-flood (from data/gfm_nonflood/*.tif)

Training data:
  flood_susceptibility/rf_training_data.csv  (already generated by train_rf_susceptibility.py)
"""

# ── install on Kaggle if needed ──────────────────────────────────────────────
import subprocess, sys

def pip_install(pkg):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])

try:
    import xgboost as xgb
except ImportError:
    pip_install("xgboost")
    import xgboost as xgb

try:
    import shap
except ImportError:
    pip_install("shap")
    import shap

# ── standard imports ─────────────────────────────────────────────────────────
import json
import os
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from sklearn.metrics import (classification_report, roc_auc_score,
                             RocCurveDisplay, ConfusionMatrixDisplay)
from sklearn.model_selection import StratifiedKFold, train_test_split

warnings.filterwarnings("ignore")

# ── paths — adapt for Kaggle vs local ────────────────────────────────────────
# On Kaggle: upload rf_training_data.csv as a dataset named "assam-flood-rf-data"
# Then set TRAINING_CSV = "/kaggle/input/assam-flood-rf-data/rf_training_data.csv"
SCRIPT_DIR   = Path(__file__).parent if "__file__" in dir() else Path(".")
TRAINING_CSV = SCRIPT_DIR / "rf_training_data.csv"
OUT_DIR      = SCRIPT_DIR

# Kaggle override — uncomment when running on Kaggle
# TRAINING_CSV = Path("/kaggle/input/assam-flood-rf-data/rf_training_data.csv")
# OUT_DIR      = Path("/kaggle/working")

FEATURES      = ["elevation", "slope", "flow_acc", "twi"]
RANDOM_STATE  = 42
N_FOLDS       = 5

# ── XGBoost hyperparameters (literature-aligned: Nagaon 2026 / boosting papers) ─
XGB_PARAMS = {
    "n_estimators":      500,
    "max_depth":         6,
    "learning_rate":     0.05,
    "subsample":         0.8,
    "colsample_bytree":  0.8,
    "min_child_weight":  5,
    "scale_pos_weight":  1,    # balanced labels; adjust if imbalanced
    "eval_metric":       "auc",
    "use_label_encoder": False,
    "random_state":      RANDOM_STATE,
    "n_jobs":            -1,
    "tree_method":       "hist",   # GPU-compatible: set to "gpu_hist" on Kaggle
}

# ── load data ─────────────────────────────────────────────────────────────────
print(f"Loading training data from: {TRAINING_CSV}")
df = pd.read_csv(TRAINING_CSV)
print(f"Total samples: {len(df)}  "
      f"(flood={df.label.sum()}, nonflood={(df.label==0).sum()})")
print(f"Districts: {df.district.value_counts().to_dict()}")
print(f"Features: {FEATURES}")

X = df[FEATURES].values
y = df["label"].values

# ── cross-validation ──────────────────────────────────────────────────────────
print(f"\n{'='*60}")
print(f"5-fold stratified cross-validation")
print(f"{'='*60}")

skf       = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=RANDOM_STATE)
fold_aucs = []

for fold, (tr_idx, va_idx) in enumerate(skf.split(X, y), 1):
    X_tr, X_va = X[tr_idx], X[va_idx]
    y_tr, y_va = y[tr_idx], y[va_idx]

    model = xgb.XGBClassifier(**XGB_PARAMS)
    model.fit(X_tr, y_tr,
              eval_set=[(X_va, y_va)],
              verbose=False)

    y_prob = model.predict_proba(X_va)[:, 1]
    auc    = roc_auc_score(y_va, y_prob)
    fold_aucs.append(auc)
    print(f"  Fold {fold}: AUC = {auc:.4f}")

print(f"\n  Mean AUC: {np.mean(fold_aucs):.4f} ± {np.std(fold_aucs):.4f}")
print(f"  RF baseline AUC: 0.8890  (from train_rf_susceptibility.py)")

# ── final model on full train/test split ──────────────────────────────────────
print(f"\n{'='*60}")
print("Final model — 80/20 train/test split")
print(f"{'='*60}")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y)

xgb_final = xgb.XGBClassifier(**XGB_PARAMS)
xgb_final.fit(X_train, y_train,
              eval_set=[(X_test, y_test)],
              verbose=False)

y_pred = xgb_final.predict(X_test)
y_prob = xgb_final.predict_proba(X_test)[:, 1]
auc    = roc_auc_score(y_test, y_prob)

report = classification_report(y_test, y_pred,
                                target_names=["nonflood", "flood"])
print(report)
print(f"ROC-AUC: {auc:.4f}")
print(f"RF baseline: 0.8890")

importances = pd.Series(xgb_final.feature_importances_, index=FEATURES)
print("\nFeature importances (gain):")
print(importances.sort_values(ascending=False).to_string())

# ── SHAP values ───────────────────────────────────────────────────────────────
print(f"\n{'='*60}")
print("SHAP analysis")
print(f"{'='*60}")

explainer  = shap.TreeExplainer(xgb_final)
shap_vals  = explainer.shap_values(X_test)

# Summary plot
fig, ax = plt.subplots(figsize=(8, 5))
shap.summary_plot(shap_vals, X_test, feature_names=FEATURES,
                  show=False, plot_type="bar")
plt.tight_layout()
shap_path = OUT_DIR / "xgb_shap_summary.png"
plt.savefig(shap_path, dpi=150, bbox_inches="tight")
plt.close()
print(f"SHAP summary saved: {shap_path}")

# Beeswarm plot
fig2, ax2 = plt.subplots(figsize=(8, 5))
shap.summary_plot(shap_vals, X_test, feature_names=FEATURES, show=False)
plt.tight_layout()
beeswarm_path = OUT_DIR / "xgb_shap_beeswarm.png"
plt.savefig(beeswarm_path, dpi=150, bbox_inches="tight")
plt.close()
print(f"SHAP beeswarm saved: {beeswarm_path}")

# ── ROC curve ─────────────────────────────────────────────────────────────────
fig3, ax3 = plt.subplots(figsize=(6, 5))
RocCurveDisplay.from_predictions(y_test, y_prob, ax=ax3,
                                  name=f"XGBoost (AUC={auc:.3f})")
ax3.plot([0, 1], [0, 1], "k--", alpha=0.5)
ax3.set_title("ROC Curve — XGBoost Flood Susceptibility")
plt.tight_layout()
roc_path = OUT_DIR / "xgb_roc_curve.png"
plt.savefig(roc_path, dpi=150, bbox_inches="tight")
plt.close()
print(f"ROC curve saved: {roc_path}")

# ── save model summary ────────────────────────────────────────────────────────
summary_lines = [
    "XGBoost Flood Susceptibility — Assam 4 Districts",
    f"Phase 1: static terrain features only (elevation, slope, TWI, flow_acc)",
    f"Training samples: {len(X_train)} | Test samples: {len(X_test)}",
    f"ROC-AUC: {auc:.4f}",
    f"CV AUC: {np.mean(fold_aucs):.4f} ± {np.std(fold_aucs):.4f}",
    "",
    report,
    "\nFeature importances (gain):",
    importances.sort_values(ascending=False).to_string(),
    "",
    "XGBoost hyperparameters:",
    str(XGB_PARAMS),
    "",
    "Comparison:",
    "  RF   ROC-AUC: 0.8890",
    f"  XGB  ROC-AUC: {auc:.4f}",
]
summary_path = OUT_DIR / "xgb_model_summary.txt"
summary_path.write_text("\n".join(summary_lines))
print(f"\nSummary saved: {summary_path}")

# ── save model ────────────────────────────────────────────────────────────────
model_path = OUT_DIR / "xgb_susceptibility_static.json"
xgb_final.save_model(str(model_path))
print(f"Model saved: {model_path}")

print(f"\n{'='*60}")
print("Done. Outputs in:", OUT_DIR)
print(f"{'='*60}")
print("\nNEXT STEP (Phase 2): add dynamic features")
print("  - Pull multi-year GloFAS ERA5 (2015-2024) for Q90 thresholds")
print("  - Add: Q_anomaly (GloFAS), 5-day rainfall accumulation (ERA5),")
print("         antecedent soil moisture (ERA5)")
print("  - Retrain with (pixel, date) as the sample unit")
